### ISSUE TITLE
html tags in blog post's code snippets.

### ISSUE THREAD

**Issue by karczex** [pmem/pmem.github.io#182]
You may see html tags in code snippets in blog posts e.g.: 
- [ ]  https://pmem.io/blog/2021/09/concurrency-considerations-in-libpmemobj-cpp/
- [x] https://pmem.io/blog/2020/10/api-overview-of-pmemkv-java-binding/
- [ ] https://pmem.io/blog/2019/02/c-persistent-containers-vector/
- [ ] https://pmem.io/blog/2019/06/multi-level-vmemcache/
- [ ] https://pmem.io/blog/2019/10/c-standard-limitations-and-persistent-memory/
- [ ] https://pmem.io/blog/2020/05/introduction-to-llpl/

![Screenshot 2021-12-15 at 16-10-45 API overview of pmemkv-java binding](https://user-images.githubusercontent.com/23352575/146212226-9dc07273-3a89-486e-bc2c-c3a790b2d7f3.png)

**Comment by lukaszstolarczuk** [comment]
Fixed in #259
